global using Microsoft.EntityFrameworkCore;
global using VOD.Films.Database;
global using VOD.Films.Database.Contexts;
global using VOD.Films.Database.Extensions;
global using Microsoft.AspNetCore.Mvc;
global using VOD.Films.Database.Entities;
global using VOD.Common.DTOs;
global using VOD.Films.API.Extensions;
global using AutoMapper;
