global using System.ComponentModel.DataAnnotations;
global using Microsoft.EntityFrameworkCore;
global using VOD.Films.Database.Entities;
global using System.Linq.Expressions;
global using VOD.Films.Database;
global using AutoMapper;
global using VOD.Films.Database.Contexts;
global using VOD.Common.DTOs;
global using System.ComponentModel.DataAnnotations.Schema;